"""Add Produto model

Revision ID: e29b811806cb
Revises: a9b32f8f9299
Create Date: 2025-11-24 15:31:39.233990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29b811806cb'
down_revision = 'a9b32f8f9299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_asin'), ['asin'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_asin'))

    op.drop_table('produtos')
    # ### end Alembic commands ###
